#!/usr/bin/bash
export GTP_U_UPSTREAM_TABLE=${GTP_U_UPSTREAM_TABLE:-10}
export GTP_U_UPSTREAM_DEV=${GTP_U_UPSTREAM_DEV:-ens5}
export GTP_U_UPSTREAM_IP4=${GTP_U_UPSTREAM_IP4:-"10.102.1.4/16"}
export GTP_U_UPSTREAM_IP4_ROUTE=${GTP_U_UPSTREAM_IP4_ROUTE:-"10.102.1.1"}

export GTP_U_GRX_TABLE=${GTP_U_GRX_TABLE:-20}
export GTP_U_GRX_DEV=${GTP_U_GRX_DEV:-ens4}
export GTP_U_GRX_IP4=${GTP_U_GRX_IP4:-"10.101.1.4/16"}
export GTP_U_GRX_IP4_ROUTE=${GTP_U_GRX_IP4_ROUTE:-"10.101.1.1"}
